import { formatObjectCountDisplay } from '../../lib/objectCount';
import { formatReadmeTimestamp } from '../../lib/readmeTimestamp';
import { appendSelectMetadataBlock } from '../datasets/selectMetadata';
import { buildAlignLabelMetadataSummary } from './alignLabelMetadata';
import type { AlignLabelFormState } from './alignLabel.types';
import type { AlignLabelTransformationRecord } from './buildAlignLabelPayload';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildAlignLabelReadmes(record: AlignLabelTransformationRecord): ReadmeFile[] {
  const timeSeriesInput = record.input_datasets.find((dataset) => dataset.id === record.align_label.time_series_dataset_id) ?? null;
  const inputNames = record.input_datasets.map((dataset) => dataset.name).join(', ');
  const annotationInput = record.input_datasets.find((dataset) => dataset.id === record.align_label.annotation_dataset_id) ?? null;
  const annotationSourceParameter = record.align_label.annotation_source === "input_dataset"
    ? `  - Annotation dataset: ${annotationInput?.name ?? "n.a."}`
    : `  - Annotation file path: ${record.align_label.label_file}`;
  const form: AlignLabelFormState = {
    timeSeriesDatasetId: record.align_label.time_series_dataset_id,
    annotationSource: record.align_label.annotation_source,
    annotationDatasetId: record.align_label.annotation_dataset_id ?? '',
    labelFilePath: record.align_label.label_file,
    labellingRule: record.align_label.labelling_rule,
    disruptionClipS: record.align_label.disruption_clip_s === null ? '' : String(record.align_label.disruption_clip_s),
    annotationSpanMarginMs: record.align_label.annotation_span_margin_ms === null ? '' : String(record.align_label.annotation_span_margin_ms),
    eventType: record.align_label.event_type,
    comments: record.comments,
  };

  return record.derived_datasets.map((dataset) => ({
    filename: `${sanitizeFilename(dataset.name || dataset.draft_id)}-README.md`,
    content: appendSelectMetadataBlock([
      `# ${dataset.name} README`,
      '',
      '## Metadata',
      `- Dataset name: ${dataset.name}`,
      `- Timestamp: ${formatReadmeTimestamp(record.created_at)}`,
      `- Type: ${capitalize(dataset.type)}`,
      '- Data object type: TimeSeries',
      `- No. of data objects: ${formatObjectCountDisplay(dataset.object_count)}`,
      `- Metadata: ${buildAlignLabelMetadataSummary(form, timeSeriesInput)}`,
      '- Generated by: AlignLabel',
      '- Parameters:',
      `  - Input datasets: ${inputNames || 'n.a.'}`,
      annotationSourceParameter,
      `  - Event type: ${record.align_label.event_type}`,
      `  - Labelling rule: ${record.align_label.labelling_rule}`,
      `  - Disruption clip (s): ${record.align_label.disruption_clip_s ?? 'n.a.'}`,
      `  - Annotation span margin (ms): ${record.align_label.annotation_span_margin_ms ?? 'n.a.'}`,
      '',
      '## User comments:',
      record.comments.trim() || 'n.a.',
      '',
    ].join('\n')),
  }));
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function sanitizeFilename(value: string) {
  return value.replace(/[^a-z0-9._-]+/gi, '-');
}
