export const routes = {
  search: '/',
  alignTS: '/transform/align-ts',
  blend: '/transform/blend',
  cropTS: '/transform/crop-ts',
  feaExSpectrogram: '/transform/fea-ex-spectrogram',
  genImage: '/transform/gen-image',
  merge: '/transform/merge',
  partition: '/transform/partition',
  sampleField: '/transform/sample-field',
  select: '/transform/select',
  sigExMAST: '/transform/sigex-mast',
  simulatePDE: '/transform/simulate-pde',
  stft: '/transform/stft',
} as const;
