import type { SelectTransformationRecord } from '../transformations/transformation.types';
import { formatReadmeTimestamp } from '../../lib/readmeTimestamp';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildSelectReadmes(record: SelectTransformationRecord, details: { variableCount: number; labelCount: number; objectCount: number }): ReadmeFile[] {
  const dataset = record.derived_datasets[0];
  const input = record.input_datasets[0];
  const userComments = record.comments.trim() || 'n.a.';

  const content = [
    '**Dataset name:**',
    `**${dataset.name}**`,
    '',
    '**Timestamp:**',
    `**${formatReadmeTimestamp(record.created_at)}**`,
    '',
    '**Generated by:**',
    '**Select**',
    '',
    '**Input datasets:**',
    `**${input.name}**`,
    '',
    '**Output dataset:**',
    `**${dataset.name}**`,
    '',
    '**Selection operations:**',
    ...record.select.operations.map((operation, index) => `**${index + 1}. ${formatOperation(operation)}**`),
    '',
    '**Number of data objects:**',
    `**${details.objectCount}**`,
    '',
    '**Number of variables:**',
    `**${details.variableCount}**`,
    '',
    '**Number of labels:**',
    `**${details.labelCount}**`,
    '',
    '**User comments:**',
    userComments,
    '',
  ].join('\n');

  return [
    {
      filename: `${sanitizeFilename(dataset.name || dataset.draft_id)}-README.md`,
      content,
    },
  ];
}

function formatOperation(operation: SelectTransformationRecord['select']['operations'][number]) {
  const base = `${capitalize(operation.scope)} | ${capitalize(operation.mode)} | ${operation.field} | ${formatOperator(operation)}`;

  if (operation.mode === 'labels') {
    return `${base} | values=[${operation.values.join(', ')}] | next=${operation.connectorToNext}`;
  }

  if (operation.values.length > 0) {
    return `${base} | variables=[${operation.values.join(', ')}] | next=${operation.connectorToNext}`;
  }

  return `${base} | next=${operation.connectorToNext}`;
}

function formatOperator(operation: SelectTransformationRecord['select']['operations'][number]) {
  if (operation.mode === 'variables' && operation.values.length > 0) {
    return operation.scope === 'across' ? 'include objects containing' : 'keep variables';
  }

  if (operation.operator === 'between') {
    return `between ${operation.minValue} and ${operation.maxValue}`;
  }

  if (operation.operator === 'gt') {
    return `> ${operation.minValue}`;
  }

  if (operation.operator === 'lt') {
    return `< ${operation.minValue}`;
  }

  if (operation.operator === 'equals') {
    return `= ${operation.minValue || operation.values.join(', ')}`;
  }

  if (operation.operator === 'notEquals') {
    return `not equals ${operation.values.join(', ')}`;
  }

  return `in ${operation.values.join(', ')}`;
}

function capitalize(value: string) {
  return `${value.charAt(0).toUpperCase()}${value.slice(1)}`;
}

function sanitizeFilename(value: string) {
  return value.replace(/[^a-z0-9-_]+/gi, '_');
}
