import type { SelectTransformationRecord } from '../transformations/transformation.types';
import { appendSelectMetadataBlock, buildSelectOutputSelectMetadata } from '../datasets/selectMetadata';
import { formatReadmeTimestamp } from '../../lib/readmeTimestamp';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildSelectReadmes(record: SelectTransformationRecord, details: { variableCount: number; labelCount: number; objectCount: number }): ReadmeFile[] {
  const dataset = record.derived_datasets[0];
  const input = record.input_datasets[0];
  const userComments = record.comments.trim() || 'n.a.';
  const selectMetadata = buildSelectOutputSelectMetadata(input, record.select.operations);

  const content = appendSelectMetadataBlock([
    `# ${dataset.name} README`,
    '',
    '## Metadata',
    `- Dataset name: ${dataset.name}`,
    `- Timestamp: ${formatReadmeTimestamp(record.created_at)}`,
    `- Type: ${capitalize(dataset.type)}`,
    `- Data object type: ${input?.dataObjectType ?? input?.modality ?? 'Dataset object'}`,
    `- No. of data objects: ${details.objectCount}`,
    `- Metadata: Selected dataset. ${details.objectCount} data objects. ${details.variableCount} columns. ${details.labelCount} label headings.`,
    '- Generated by: Select',
    '- Parameters: ',
    `  - Input datasets: ${input.name}`,
    `  - Selection operations: ${record.select.operations.map((operation, index) => `${index + 1}. ${formatOperation(operation, index < record.select.operations.length - 1)}`).join(' ; ') || 'n.a.'}`,
    '',
    '## User comments:',
    userComments,
    '',
  ].join('\n'), selectMetadata);

  return [
    {
      filename: `${sanitizeFilename(dataset.name || dataset.draft_id)}-README.md`,
      content,
    },
  ];
}

function formatOperation(operation: SelectTransformationRecord['select']['operations'][number], hasNext: boolean) {
  const base = `${formatScope(operation)} | ${capitalize(operation.mode)} | ${operation.field} | ${formatOperator(operation)}`;

  if (operation.mode === 'labels') {
    if (operation.labelSelectionMode === 'proportion') {
      return `${base} | random_proportion=${operation.labelProportion} | seed=${operation.labelRandomSeed}${hasNext ? ` | next=${operation.connectorToNext}` : ''}`;
    }

    return `${base} | values=[${operation.values.join(', ')}]${hasNext ? ` | next=${operation.connectorToNext}` : ''}`;
  }

  if (operation.values.length > 0) {
    return `${base} | columns=[${operation.values.join(', ')}]${hasNext ? ` | next=${operation.connectorToNext}` : ''}`;
  }

  return `${base}${hasNext ? ` | next=${operation.connectorToNext}` : ''}`;
}


function formatScope(operation: SelectTransformationRecord['select']['operations'][number]) {
  if (operation.mode === 'labels') {
    return operation.scope === 'across' ? 'Select data objects by labels' : 'Filter within data objects by labels';
  }

  return operation.scope === 'across' ? 'Select data objects by columns' : 'Filter within data objects by columns';
}

function formatOperator(operation: SelectTransformationRecord['select']['operations'][number]) {
  if (operation.mode === 'labels' && operation.labelSelectionMode === 'proportion') {
    return 'select label groups by random proportion';
  }

  if (operation.mode === 'variables' && operation.values.length > 0) {
    return operation.scope === 'across' ? 'include objects containing' : 'keep columns';
  }

  if (operation.operator === 'between') {
    return `between ${operation.minValue} and ${operation.maxValue}`;
  }

  if (operation.operator === 'gt') {
    return `> ${operation.minValue}`;
  }

  if (operation.operator === 'lt') {
    return `< ${operation.minValue}`;
  }

  if (operation.operator === 'equals') {
    return `= ${operation.minValue || operation.values.join(', ')}`;
  }

  if (operation.operator === 'notEquals') {
    return `not equals ${operation.values.join(', ')}`;
  }

  return `in ${operation.values.join(', ')}`;
}

function capitalize(value: string) {
  return `${value.charAt(0).toUpperCase()}${value.slice(1)}`;
}

function sanitizeFilename(value: string) {
  return value.replace(/[^a-z0-9-_]+/gi, '_');
}
