import { formatReadmeTimestamp } from '../../lib/readmeTimestamp';
import { formatObjectCountDisplay } from '../../lib/objectCount';
import { appendSelectMetadataBlock } from '../datasets/selectMetadata';
import { buildAlignTSMetadataSummary } from './alignTSMetadata';
import type { AlignTSTransformationRecord } from './buildAlignTSPayload';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildAlignTSReadmes(record: AlignTSTransformationRecord): ReadmeFile[] {
  const input = record.input_datasets[0];

  return record.derived_datasets.map((dataset) => ({
    filename: `${dataset.name}_README.md`,
    content: appendSelectMetadataBlock([
      `# ${dataset.name} README`,
      '',
      '## Metadata',
      `- Dataset name: ${dataset.name}`,
      `- Timestamp: ${formatReadmeTimestamp(record.created_at)}`,
      `- Type: ${capitalize(dataset.type)}`,
      '- Data object type: TimeSeries',
      `- No. of data objects: ${formatObjectCountDisplay(dataset.object_count)}`,
      `- Metadata: ${buildAlignTSMetadataSummary({
        tMin: record.align_ts.t_min,
        tMax: record.align_ts.t_max === null ? '' : String(record.align_ts.t_max),
        dt: record.align_ts.dt,
        method: record.align_ts.method,
        comments: '',
      })}`,
      '- Generated by: AlignTS',
      '- Parameters:',
      `  - Input datasets: ${input?.name ?? 'Unknown input dataset'}`,
      `  - t_min: ${record.align_ts.t_min}`,
      `  - t_max: ${record.align_ts.t_max === null ? 'signal max' : record.align_ts.t_max}`,
      `  - dt: ${record.align_ts.dt}`,
      `  - method: ${record.align_ts.method}`,
      '',
      '## User comments:',
      record.comments.trim() || 'n.a.',
      '',
    ].join('\n'), input?.selectMetadata),
  }));
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}
