import { formatObjectCountDisplay } from '../../lib/objectCount';
import { formatReadmeTimestamp } from '../../lib/readmeTimestamp';
import { appendSelectMetadataBlock } from '../datasets/selectMetadata';
import type { SegmentTSTransformationRecord } from './buildSegmentTSPayload';
import { buildSegmentTSMetadataSummary, getSegmentTSCalculations } from './segmentTSMetadata';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildSegmentTSReadmes(record: SegmentTSTransformationRecord): ReadmeFile[] {
  const input = record.input_datasets[0];
  const form = {
    windowMs: String(record.segment_ts.window_ms),
    strideMs: String(record.segment_ts.stride_ms),
    fsHz: String(record.segment_ts.fs_hz),
    comments: record.comments,
  };
  const calculations = getSegmentTSCalculations(form);

  return record.derived_datasets.map((dataset) => ({
    filename: `${sanitizeFilename(dataset.name || dataset.draft_id)}-README.md`,
    content: appendSelectMetadataBlock([
      `# ${dataset.name} README`,
      '',
      '## Metadata',
      `- Dataset name: ${dataset.name}`,
      `- Timestamp: ${formatReadmeTimestamp(record.created_at)}`,
      `- Type: ${capitalize(dataset.type)}`,
      '- Data object type: TimeSeries',
      `- No. of data objects: ${formatObjectCountDisplay(dataset.object_count)}`,
      `- Metadata: ${buildSegmentTSMetadataSummary(form)}`,
      '- Generated by: SegmentTS',
      '- Parameters:',
      `  - Input datasets: ${input?.name ?? 'Unknown input dataset'}`,
      `  - window_ms: ${record.segment_ts.window_ms}`,
      `  - stride_ms: ${record.segment_ts.stride_ms}`,
      `  - fs_hz: ${record.segment_ts.fs_hz}`,
      `  - window_samples: ${calculations.windowSamples ?? 'n.a.'}`,
      `  - stride_samples: ${calculations.strideSamples ?? 'n.a.'}`,
      '',
      '## User comments:',
      record.comments.trim() || 'n.a.',
      '',
    ].join('\n'), input?.selectMetadata),
  }));
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function sanitizeFilename(value: string) {
  return value.replace(/[^a-z0-9._-]+/gi, '-');
}
