import { formatObjectCountDisplay } from '../../lib/objectCount';
import { formatReadmeTimestamp } from '../../lib/readmeTimestamp';
import { appendSelectMetadataBlock } from '../datasets/selectMetadata';
import { buildCropTSMetadataSummary } from './cropTSMetadata';
import type { CropTSTransformationRecord } from './buildCropTSPayload';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildCropTSReadmes(record: CropTSTransformationRecord): ReadmeFile[] {
  const input = record.input_datasets[0];

  return record.derived_datasets.map((dataset) => ({
    filename: `${dataset.name}_README.md`,
    content: appendSelectMetadataBlock([
      `# ${dataset.name} README`,
      '',
      '## Metadata',
      `- Dataset name: ${dataset.name}`,
      `- Timestamp: ${formatReadmeTimestamp(record.created_at)}`,
      `- Type: ${capitalize(dataset.type)}`,
      '- Data object type: TimeSeries',
      `- No. of data objects: ${formatObjectCountDisplay(dataset.object_count)}`,
      `- Metadata: ${buildCropTSMetadataSummary({
        ipThresholdKa: record.crop_ts.ip_threshold_ka,
        flattopMinFrac: record.crop_ts.flattop_min_frac,
        flattopTrimStartFrac: record.crop_ts.flattop_trim_start_frac === null ? '' : String(record.crop_ts.flattop_trim_start_frac),
        flattopTrimEndFrac: record.crop_ts.flattop_trim_end_frac === null ? '' : String(record.crop_ts.flattop_trim_end_frac),
        comments: '',
      })}`,
      '- Generated by: CropTS',
      '- Parameters:',
      `  - Input datasets: ${input?.name ?? 'Unknown input dataset'}`,
      `  - ip_threshold_ka: ${record.crop_ts.ip_threshold_ka}`,
      `  - flattop_min_frac: ${record.crop_ts.flattop_min_frac}`,
      `  - flattop_trim_start_frac: ${record.crop_ts.flattop_trim_start_frac ?? 'n.a.'}`,
      `  - flattop_trim_end_frac: ${record.crop_ts.flattop_trim_end_frac ?? 'n.a.'}`,
      '',
      '## User comments:',
      record.comments.trim() || 'n.a.',
      '',
    ].join('\n'), input?.selectMetadata),
  }));
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}
