import type { PartitionTransformationRecord } from '../transformations/transformation.types';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildPartitionReadmes(record: PartitionTransformationRecord): ReadmeFile[] {
  return record.derived_datasets.map((dataset) => {
    const parentDataset = record.input_datasets.find((input) => input.id === dataset.parent_id);
    const userComments = record.comments.trim() || 'n.a.';

    const content = [
      '**Dataset name:**',
      `**${dataset.name}**`,
      '',
      '**Generated by:**',
      '**Partition**',
      '',
      '**Input datasets:**',
      `**${formatDatasetEntry(parentDataset?.name ?? dataset.parent_id, dataset.parent_id)}**`,
      '',
      '**Output dataset:**',
      `**${formatDatasetEntry(dataset.name, dataset.draft_id)}**`,
      '',
      '**Partition strategy:**',
      `**${record.partition.method}**`,
      '',
      '**Partition parameter:**',
      `**${formatPartitionParameter(record)}**`,
      '',
      '**Number of data objects:**',
      `**${dataset.object_count}**`,
      '',
      '**User comments:**',
      userComments,
      '',
    ].join('\n');

    return {
      filename: `${sanitizeFilename(dataset.name || dataset.draft_id)}-README.md`,
      content,
    };
  });
}

function formatPartitionParameter(record: PartitionTransformationRecord) {
  const ratios = [record.partition.train_ratio, record.partition.validation_ratio, record.partition.test_ratio]
    .map((value) => value.toFixed(2))
    .join(', ');

  if (record.partition.method === 'random') {
    return `ratios=(${ratios}), seed=${record.partition.random_seed}`;
  }

  return `ratios=(${ratios})`;
}

function formatDatasetEntry(name: string, id: string) {
  return `${name} (${id})`;
}

function sanitizeFilename(value: string) {
  return value.replace(/[^a-z0-9-_]+/gi, '_');
}
