import { getDatasetDataObjectType } from '../datasets/dataObjectType';
import type { PartitionTransformationRecord } from '../transformations/transformation.types';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildPartitionReadmes(record: PartitionTransformationRecord): ReadmeFile[] {
  return record.derived_datasets.map((dataset) => {
    const parentDataset = record.input_datasets.find((input) => input.id === dataset.parent_id);
    const userComments = record.comments.trim() || 'n.a.';

    const content = [
      `# ${dataset.name} README`,
      '',
      '## Metadata',
      `- Dataset name: ${dataset.name}`,
      `- Type: ${capitalize(dataset.type)}`,
      `- Data object type: ${getDatasetDataObjectType(parentDataset ?? { name: dataset.name, modality: 'Dataset object', dataObjectType: undefined })}`,
      `- No. of data objects: ${dataset.object_count}`,
      `- Metadata: ${parentDataset?.metadataSummary ?? 'n.a.'}`,
      '- Generated by: Partition',
      '- Parameters: ',
      `  - Input datasets: ${parentDataset?.name ?? 'Unknown input dataset'}`,
      `  - Partition strategy: ${record.partition.method}`,
      `  - Ratios: (${record.partition.train_ratio.toFixed(2)}, ${record.partition.validation_ratio.toFixed(2)}, ${record.partition.test_ratio.toFixed(2)})`,
      ...(record.partition.method === 'random' ? [`  - Seed: ${record.partition.random_seed}`] : []),
      '',
      '## User comments:\t',
      userComments,
      '',
    ].join('\n');

    return {
      filename: `${sanitizeFilename(dataset.name || dataset.draft_id)}-README.md`,
      content,
    };
  });
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function sanitizeFilename(value: string) {
  return value.replace(/[^a-z0-9-_]+/gi, '_');
}
