import { formatObjectCountDisplay } from '../../lib/objectCount';
import { formatReadmeTimestamp } from '../../lib/readmeTimestamp';
import { appendSelectMetadataBlock } from '../datasets/selectMetadata';
import type { NormTSTransformationRecord } from './buildNormTSPayload';
import { buildNormTSMetadataSummary } from './normTSMetadata';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildNormTSReadmes(record: NormTSTransformationRecord): ReadmeFile[] {
  const input = record.input_datasets[0];

  return record.derived_datasets.map((dataset) => ({
    filename: `${sanitizeFilename(dataset.name || dataset.draft_id)}-README.md`,
    content: appendSelectMetadataBlock([
      `# ${dataset.name} README`,
      '',
      '## Metadata',
      `- Dataset name: ${dataset.name}`,
      `- Timestamp: ${formatReadmeTimestamp(record.created_at)}`,
      `- Type: ${capitalize(dataset.type)}`,
      '- Data object type: TimeSeries',
      `- No. of data objects: ${formatObjectCountDisplay(dataset.object_count)}`,
      `- Metadata: ${buildNormTSMetadataSummary({ method: record.norm_ts.method, epsilon: record.norm_ts.epsilon, fitScope: record.norm_ts.fit_scope })}`,
      '- Generated by: NormTS',
      '- Parameters:',
      `  - Input datasets: ${input?.name ?? 'Unknown input dataset'}`,
      `  - method: ${record.norm_ts.method}`,
      `  - epsilon: ${record.norm_ts.epsilon}`,
      `  - fit_scope: ${record.norm_ts.fit_scope}`,
      '',
      '## User comments:',
      record.comments.trim() || 'n.a.',
      '',
    ].join('\n'), input?.selectMetadata),
  }));
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function sanitizeFilename(value: string) {
  return value.replace(/[^a-z0-9._-]+/gi, '-');
}
