import { formatObjectCountDisplay } from '../../lib/objectCount';
import { formatReadmeTimestamp } from '../../lib/readmeTimestamp';
import { appendSelectMetadataBlock } from '../datasets/selectMetadata';
import type { ImputeTSTransformationRecord } from './buildImputeTSPayload';
import { buildImputeTSMetadataSummary } from './imputeTSMetadata';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildImputeTSReadmes(record: ImputeTSTransformationRecord): ReadmeFile[] {
  const input = record.input_datasets[0];

  return record.derived_datasets.map((dataset) => ({
    filename: `${sanitizeFilename(dataset.name || dataset.draft_id)}-README.md`,
    content: appendSelectMetadataBlock([
      `# ${dataset.name} README`,
      '',
      '## Metadata',
      `- Dataset name: ${dataset.name}`,
      `- Timestamp: ${formatReadmeTimestamp(record.created_at)}`,
      `- Type: ${capitalize(dataset.type)}`,
      '- Data object type: TimeSeries',
      `- No. of data objects: ${formatObjectCountDisplay(dataset.object_count)}`,
      `- Metadata: ${buildImputeTSMetadataSummary({ fillStrategy: record.impute_ts.fill_strategy, minValidSamples: record.impute_ts.min_valid_samples, comments: '' })}`,
      '- Generated by: ImputeTS',
      '- Parameters:',
      `  - Input datasets: ${input?.name ?? 'Unknown input dataset'}`,
      `  - fill_strategy: ${record.impute_ts.fill_strategy}`,
      `  - min_valid_samples: ${record.impute_ts.min_valid_samples}`,
      '',
      '## User comments:',
      record.comments.trim() || 'n.a.',
      '',
    ].join('\n'), input?.selectMetadata),
  }));
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function sanitizeFilename(value: string) {
  return value.replace(/[^a-z0-9._-]+/gi, '-');
}
