import type { SampleFieldTransformationRecord } from '../transformations/transformation.types';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildSampleFieldReadmes(record: SampleFieldTransformationRecord): ReadmeFile[] {
  return record.derived_datasets.map((dataset) => {
    const parentDataset = record.input_datasets.find((input) => input.id === dataset.parent_id);
    const userComments = record.comments.trim() || 'n.a.';

    const content = [
      '**Dataset name:**',
      `**${dataset.name}**`,
      '',
      '**Generated by:**',
      '**SampleField**',
      '',
      '**Input datasets:**',
      `**${formatDatasetEntry(parentDataset?.name ?? dataset.parent_id, dataset.parent_id)}**`,
      '',
      '**Output dataset:**',
      `**${formatDatasetEntry(dataset.name, dataset.draft_id)}**`,
      '',
      '**Random seed:**',
      `**${record.sample_field.random_seed}**`,
      '',
      '**Number of data objects:**',
      `**${record.sample_field.number_of_data_objects}**`,
      '',
      '**Number of samples per object:**',
      `**${record.sample_field.number_of_samples_per_object}**`,
      '',
      '**User comments:**',
      userComments,
      '',
    ].join('\n');

    return {
      filename: `${sanitizeFilename(dataset.name || dataset.draft_id)}-README.md`,
      content,
    };
  });
}

function formatDatasetEntry(name: string, id: string) {
  return `${name} (${id})`;
}

function sanitizeFilename(value: string) {
  return value.replace(/[^a-z0-9-_]+/gi, '_');
}
