import { getDatasetDataObjectType } from '../datasets/dataObjectType';
import type { SampleFieldTransformationRecord } from '../transformations/transformation.types';
import { formatReadmeTimestamp } from '../../lib/readmeTimestamp';
import { appendSelectMetadataBlock } from '../datasets/selectMetadata';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildSampleFieldReadmes(record: SampleFieldTransformationRecord): ReadmeFile[] {
  return record.derived_datasets.map((dataset) => {
    const parentDataset = record.input_datasets.find((input) => input.id === dataset.parent_id);
    const userComments = record.comments.trim() || 'n.a.';
    const inheritedMetadata = appendSamplePoints(
      parentDataset?.metadataSummary ?? 'n.a.',
      record.sample_field.number_of_samples_per_object,
    );

    const content = appendSelectMetadataBlock([
      `# ${dataset.name} README`,
      '',
      '## Metadata',
      `- Dataset name: ${dataset.name}`,
      `- Timestamp: ${formatReadmeTimestamp(record.created_at)}`,
      `- Type: ${capitalize(dataset.type)}`,
      `- Data object type: ${getDatasetDataObjectType(parentDataset ?? { name: dataset.name, modality: 'Field', dataObjectType: 'Field' })}`,
      `- No. of data objects: ${dataset.object_count}`,
      `- Metadata: ${inheritedMetadata}`,
      '- Generated by: SampleField',
      '- Parameters: ',
      `  - Input datasets: ${parentDataset?.name ?? 'Unknown input dataset'}`,
      `  - Random seed: ${record.sample_field.random_seed}`,
      `  - No. of data objects: ${record.sample_field.number_of_data_objects}`,
      `  - No. of samples per objects: ${record.sample_field.number_of_samples_per_object}`,
      '',
      '## User comments:\t',
      userComments,
      '',
    ].join('\n'), parentDataset?.selectMetadata);

    return {
      filename: `${sanitizeFilename(dataset.name || dataset.draft_id)}-README.md`,
      content,
    };
  });
}

function appendSamplePoints(metadata: string, samplePoints: number) {
  const trimmed = metadata.trim();

  if (!trimmed || trimmed === 'n.a.') {
    return `${samplePoints} sample points.`;
  }

  return `${trimmed}${trimmed.endsWith('.') ? '' : '.'} ${samplePoints} sample points.`;
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function sanitizeFilename(value: string) {
  return value.replace(/[^a-z0-9-_]+/gi, '_');
}
