import type { SimulatePDETransformationRecord } from '../transformations/transformation.types';
import { formatReadmeTimestamp } from '../../lib/readmeTimestamp';
import { appendSelectMetadataBlock } from '../datasets/selectMetadata';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildSimulatePDEReadmes(record: SimulatePDETransformationRecord): ReadmeFile[] {
  return record.derived_datasets.map((dataset) => {
    const parentDataset = record.input_datasets.find((input) => input.id === dataset.parent_id);
    const content = appendSelectMetadataBlock([
      `# ${dataset.name} README`,
      '',
      '## Metadata',
      `- Dataset name: ${dataset.name}`,
      `- Timestamp: ${formatReadmeTimestamp(record.created_at)}`,
      `- Type: ${capitalize(dataset.type)}`,
      '- Data object type: Field',
      `- No. of data objects: ${dataset.object_count}`,
      `- Metadata: ${formatMetadata(record)}`,
      '- Generated by: SimulatePDE',
      '- Parameters: ',
      `  - Input datasets: ${parentDataset?.name ?? 'Unknown input dataset'}`,
      `  - Solver method: ${formatSolver(record)}`,
      `  - Equation type: ${formatEquationType(record)}`,
      `  - Spatial: ${record.simulate_pde.spatial_dimension.toUpperCase()}`,
      `  - Temporal: ${record.simulate_pde.has_temporal_dimension ? 'True' : 'False'}`,
      `  - Boundary condition: ${record.simulate_pde.boundary_condition}`,
      `  - Dimension 1: xmin = ${record.simulate_pde.x_range[0]}, xmax = ${record.simulate_pde.x_range[1]}, xstep = ${record.simulate_pde.x_step}`,
      ...(record.simulate_pde.spatial_dimension === '2d' && record.simulate_pde.y_range && record.simulate_pde.y_step !== null
        ? [`  - Dimension 2: ymin = ${record.simulate_pde.y_range[0]}, ymax = ${record.simulate_pde.y_range[1]}, ystep = ${record.simulate_pde.y_step}`]
        : []),
      ...(record.simulate_pde.has_temporal_dimension && record.simulate_pde.t_range && record.simulate_pde.t_step !== null
        ? [`  - Temporal Dimension: tmin = ${record.simulate_pde.t_range[0]}, tmax = ${record.simulate_pde.t_range[1]}, tstep = ${record.simulate_pde.t_step}`]
        : []),
      '',
      '## User comments:\t',
      record.comments.trim() || 'n.a.',
      '',
    ].join('\n'), parentDataset?.selectMetadata);

    return {
      filename: `${sanitizeFilename(dataset.name || dataset.draft_id)}-README.md`,
      content,
    };
  });
}

function formatMetadata(record: SimulatePDETransformationRecord) {
  const prefix = record.simulate_pde.has_temporal_dimension ? 'Spatio-temporal field.' : 'Spatial field.';
  const parts = [
    `x = (${record.simulate_pde.x_range[0]},${record.simulate_pde.x_range[1]})`,
    `xstep = ${record.simulate_pde.x_step}`,
  ];

  if (record.simulate_pde.spatial_dimension === '2d' && record.simulate_pde.y_range && record.simulate_pde.y_step !== null) {
    parts.push(`y = (${record.simulate_pde.y_range[0]},${record.simulate_pde.y_range[1]})`);
    parts.push(`ystep = ${record.simulate_pde.y_step}`);
  }

  if (record.simulate_pde.has_temporal_dimension && record.simulate_pde.t_range && record.simulate_pde.t_step !== null) {
    parts.push(`t = (${record.simulate_pde.t_range[0]},${record.simulate_pde.t_range[1]})`);
    parts.push(`tstep = ${record.simulate_pde.t_step}`);
  }

  return `${prefix} ${parts.join(', ')}`;
}

function formatSolver(record: SimulatePDETransformationRecord) {
  switch (record.simulate_pde.solver_method) {
    case 'fdm':
      return 'Finite Difference Method (FDM)';
    case 'fem':
      return 'Finite Element Method (FEM)';
    default:
      return 'Spectral Method';
  }
}

function formatEquationType(record: SimulatePDETransformationRecord) {
  switch (record.simulate_pde.equation_type) {
    case 'second_order_hyperbolic':
      return '2nd-order hyperbolic PDE';
    case 'elliptic':
      return 'Elliptic PDE';
    default:
      return 'Parabolic PDE';
  }
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function sanitizeFilename(value: string) {
  return value.replace(/[^a-z0-9-_]+/gi, '_');
}
