import { appendSelectMetadataBlock } from '../datasets/selectMetadata';
import { formatReadmeTimestamp } from '../../lib/readmeTimestamp';
import { formatObjectCountDisplay } from '../../lib/objectCount';
import type { SigExMASTTransformationRecord } from '../transformations/transformation.types';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildSigExMASTReadmes(record: SigExMASTTransformationRecord): ReadmeFile[] {
  return record.derived_datasets.map((dataset) => {
    const userComments = record.comments.trim() || 'n.a.';
    const inputNames = record.input_datasets.map((input) => input.name).join(', ');
    const shotDatasetName = record.input_datasets.find((input) => input.id === record.sig_ex_mast.shot_dataset_id)?.name;
    const extraShotLine = record.sig_ex_mast.shot_source === 'input_dataset'
      ? `  - Shot dataset: ${shotDatasetName ?? 'n.a.'}`
      : record.sig_ex_mast.shot_source === 'input_path'
        ? `  - Shot path: ${record.sig_ex_mast.shot_path ?? 'n.a.'}`
        : `  - Shot IDs: ${record.sig_ex_mast.shot_ids.join(', ') || 'n.a.'}`;

    const content = appendSelectMetadataBlock([
      `# ${dataset.name} README`,
      '',
      '## Metadata',
      `- Dataset name: ${dataset.name}`,
      `- Timestamp: ${formatReadmeTimestamp(record.created_at)}`,
      `- Type: ${capitalize(dataset.type)}`,
      '- Data object type: TimeSeries',
      `- No. of data objects: ${formatObjectCountDisplay(dataset.object_count)}`,
      `- Metadata: Retrieved raw time-series signals. Irregular sampling. Signals: ${record.sig_ex_mast.channels.join(', ')}.`,
      '- Generated by: SigExMAST',
      '- Parameters: ',
      `  - Input datasets: ${inputNames}`,
      `  - Campaign: ${record.sig_ex_mast.campaign}`,
      `  - Shot source: ${formatShotSource(record.sig_ex_mast.shot_source)}`,
      extraShotLine,
      `  - Signals: ${record.sig_ex_mast.channels.join(', ')}`,
      '',
      '## User comments:',
      userComments,
      '',
    ].join('\n'), record.input_datasets[0]?.selectMetadata);

    return {
      filename: `${sanitizeFilename(dataset.name || dataset.draft_id)}-README.md`,
      content,
    };
  });
}

function formatShotSource(value: SigExMASTTransformationRecord['sig_ex_mast']['shot_source']) {
  if (value === 'input_dataset') return 'input dataset';
  if (value === 'input_path') return 'input path';
  return 'manual shot IDs';
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function sanitizeFilename(value: string) {
  return value.replace(/[^a-z0-9-_]+/gi, '_');
}
