import type { FeaExSpectrogramTransformationRecord } from '../transformations/transformation.types';
import { buildFeaExSpectrogramMetadataSummary, formatSelectedComponents } from './feaExSpectrogramMetadata';
import { formatReadmeTimestamp } from '../../lib/readmeTimestamp';
import { appendSelectMetadataBlock } from '../datasets/selectMetadata';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildFeaExSpectrogramReadmes(record: FeaExSpectrogramTransformationRecord): ReadmeFile[] {
  const input = record.input_datasets[0];

  return record.derived_datasets.map((dataset) => ({
    filename: `${dataset.name}_README.md`,
    content: appendSelectMetadataBlock([
      `# ${dataset.name} README`,
      '',
      '## Metadata',
      `- Dataset name: ${dataset.name}`,
      `- Timestamp: ${formatReadmeTimestamp(record.created_at)}`,
      `- Type: ${capitalize(dataset.type)}`,
      '- Data object type: STFT / Feature',
      `- No. of data objects: ${dataset.object_count}`,
      `- Metadata: ${buildFeaExSpectrogramMetadataSummary(input, {
        selectedComponents: record.fea_ex_spectrogram.selected_components,
        preserveLabelAssociations: record.fea_ex_spectrogram.preserve_label_associations,
        advancedInstruction: record.fea_ex_spectrogram.advanced_instruction,
      })}`,
      '- Generated by: FeaExSpectrogram',
      '- Parameters:',
      `  - Input datasets: ${input?.name ?? 'Unknown input dataset'}`,
      `  - Selected components: ${formatSelectedComponents(record.fea_ex_spectrogram.selected_components)}`,
      `  - Preserve label associations: ${record.fea_ex_spectrogram.preserve_label_associations ? 'True' : 'False'}`,
      `  - Enable advanced extraction: ${record.fea_ex_spectrogram.enable_advanced_extraction ? 'True' : 'False'}`,
      '  - Source representation: STFT',
      ...(record.fea_ex_spectrogram.enable_advanced_extraction && record.fea_ex_spectrogram.advanced_instruction.trim()
        ? [`  - Advanced extraction instruction: ${record.fea_ex_spectrogram.advanced_instruction.trim()}`]
        : []),
      '',
      '## User comments:',
      record.comments.trim() || 'n.a.',
      '',
    ].join('\n'), input?.selectMetadata),
  }));
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}
