import { buildAddLabelMetadataSummary, buildMergeMetadataSummary, getHomogeneousMergeDataObjectType } from './mergeMetadata';
import type { MergeTransformationRecord } from '../transformations/transformation.types';
import { formatReadmeTimestamp } from '../../lib/readmeTimestamp';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildMergeReadmes(record: MergeTransformationRecord): ReadmeFile[] {
  return record.derived_datasets.map((dataset) => {
    const orderedInputs = record.merge.input_order
      .map((id) => record.input_datasets.find((input) => input.id === id))
      .filter((input): input is NonNullable<typeof input> => Boolean(input));

    if (record.merge.method === 'complex' && record.merge.complex_operation === 'add_label' && record.merge.add_label) {
      const primaryDataset = record.input_datasets.find((input) => input.id === record.merge.add_label?.primary_dataset_id) ?? null;
      const labelDatasets = record.input_datasets.filter((input) => record.merge.add_label?.label_dataset_ids.includes(input.id));
      const metadata = buildAddLabelMetadataSummary(
        primaryDataset ? { ...primaryDataset, objectCount: dataset.object_count } : null,
        labelDatasets,
        record.merge.add_label.duplicate_primary_dataset,
        record.merge.add_label.label_headings_by_source,
      );
      const selectedSourceNames = [
        ...(record.merge.add_label.duplicate_primary_dataset && primaryDataset ? [primaryDataset.name] : []),
        ...labelDatasets.map((input) => input.name),
      ];
      const selectedHeadings = [
        ...(record.merge.add_label.duplicate_primary_dataset ? [record.merge.add_label.label_headings_by_source.duplicate_primary].filter(Boolean) : []),
        ...labelDatasets.map((input) => record.merge.add_label?.label_headings_by_source[input.id]).filter(Boolean),
      ];

      return {
        filename: `${sanitizeFilename(dataset.name || dataset.draft_id)}-README.md`,
        content: [
          `# ${dataset.name} README`,
          '',
          '## Metadata',
          `- Dataset name: ${dataset.name}`,
        `- Timestamp: ${formatReadmeTimestamp(record.created_at)}`,
          `- Timestamp: ${formatReadmeTimestamp(record.created_at)}`,
          `- Type: ${capitalize(dataset.type)}`,
          `- Data object type: ${primaryDataset?.dataObjectType ?? primaryDataset?.modality ?? 'Dataset object'}`,
          `- No. of data objects: ${dataset.object_count}`,
          `- Metadata: ${metadata}`,
          '- Generated by: AddLabel',
          '- Parameters: ',
          `  - Input datasets: ${record.input_datasets.map((input) => input.name).join(', ') || 'n.a.'}`,
          `  - Primary dataset: ${primaryDataset?.name ?? 'n.a.'}`,
          `  - Label sources: ${selectedSourceNames.join(', ') || 'n.a.'}`,
          `  - Association rule: ${record.merge.add_label.association_rule}`,
          `  - Label headings: ${selectedHeadings.join(', ') || 'n.a.'}`,
          '',
          '## User comments:	',
          record.comments.trim() || 'n.a.',
          '',
        ].join('\n'),
      };
    }

    const dataObjectType = getHomogeneousMergeDataObjectType(orderedInputs) ?? 'Mixed input types';
    const mergedMetadata = buildMergeMetadataSummary(orderedInputs, dataset.object_count, record.merge.mode ?? 'attach');
    const userComments = record.comments.trim() || 'n.a.';

    return {
      filename: `${sanitizeFilename(dataset.name || dataset.draft_id)}-README.md`,
      content: [
        `# ${dataset.name} README`,
        '',
        '## Metadata',
        `- Dataset name: ${dataset.name}`,
        `- Type: ${capitalize(dataset.type)}`,
        `- Data object type: ${dataObjectType}`,
        `- No. of data objects: ${dataset.object_count}`,
        `- Metadata: ${mergedMetadata}`,
        '- Generated by: Merge',
        '- Parameters: ',
        `  - Input datasets: ${orderedInputs.map((input) => input.name).join(', ') || 'n.a.'}`,
        '  - Merge method: data_objects',
        `  - Data-object merge mode: ${record.merge.mode ?? 'attach'}`,
        ...((record.merge.mode ?? 'attach') === 'attach'
          ? [`  - Input order: ${orderedInputs.map((input) => input.name).join(' -> ')}`]
          : [`  - Seed: ${record.merge.random_seed ?? 0}`]),
        '',
        '## User comments:	',
        userComments,
        '',
      ].join('\n'),
    };
  });
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function sanitizeFilename(value: string) {
  return value.replace(/[^a-z0-9-_]+/gi, '_');
}
