import type { STFTTransformationRecord } from '../transformations/transformation.types';
import { buildSTFTMetadataSummary, formatWindowType } from './stftMetadata';
import { formatReadmeTimestamp } from '../../lib/readmeTimestamp';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildSTFTReadmes(record: STFTTransformationRecord): ReadmeFile[] {
  const input = record.input_datasets[0];

  return record.derived_datasets.map((dataset) => ({
    filename: `${dataset.name}_README.md`,
    content: [
      `# ${dataset.name} README`,
      '',
      '## Metadata',
      `- Dataset name: ${dataset.name}`,
      `- Timestamp: ${formatReadmeTimestamp(record.created_at)}`,
      `- Type: ${capitalize(dataset.type)}`,
      '- Data object type: STFT',
      `- No. of data objects: ${dataset.object_count}`,
      `- Metadata: ${buildSTFTMetadataSummary(input, {
        windowType: record.stft.window_type,
        fftSize: record.stft.fft_size,
        windowLength: record.stft.window_length,
        hopLength: record.stft.hop_length,
        applyToLabels: record.stft.apply_to_labels,
      })}`,
      '- Generated by: STFT',
      '- Parameters:',
      `  - Input datasets: ${input?.name ?? 'Unknown input dataset'}`,
      `  - Sample rate: ${record.stft.sample_rate}`,
      `  - FFT size: ${record.stft.fft_size}`,
      `  - Window length: ${record.stft.window_length}`,
      `  - Hop length: ${record.stft.hop_length}`,
      `  - Window type: ${formatWindowType(record.stft.window_type)}`,
      '  - Output representation: STFT',
      `  - Apply STFT to labels: ${record.stft.apply_to_labels ? 'True' : 'False'}`,
      '',
      '## User comments:',
      record.comments.trim() || 'n.a.',
      '',
    ].join('\n'),
  }));
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}
