import type { GenImageTransformationRecord } from '../transformations/transformation.types';
import { formatReadmeTimestamp } from '../../lib/readmeTimestamp';
import { appendSelectMetadataBlock, buildGenImageSelectMetadata } from '../datasets/selectMetadata';

interface ReadmeFile {
  filename: string;
  content: string;
}

const VARIABLE_CONFIG = [
  { key: 'shape', label: 'shape' },
  { key: 'scale', label: 'scale' },
  { key: 'size', label: 'size' },
  { key: 'pos_x', label: 'pos_x' },
  { key: 'pos_y', label: 'pos_y' },
  { key: 'rotation', label: 'rotation' },
  { key: 'grey', label: 'grey' },
] as const;

const RANGE_VARIABLE_CONFIG = VARIABLE_CONFIG.filter((item) => item.key !== 'shape') as Array<{
  key: 'scale' | 'size' | 'pos_x' | 'pos_y' | 'rotation' | 'grey';
  label: string;
}>;

export function buildGenImageReadmes(record: GenImageTransformationRecord): ReadmeFile[] {
  const dataset = record.derived_datasets[0];
  const input = record.input_datasets[0];
  const metadata = formatMetadata(record);

  return [
    {
      filename: `${sanitizeFilename(dataset.name || dataset.draft_id)}-README.md`,
      content: appendSelectMetadataBlock([
        `# ${dataset.name} README`,
        '',
        '## Metadata',
        `- Dataset name: ${dataset.name}`,
        `- Timestamp: ${formatReadmeTimestamp(record.created_at)}`,
        `- Type: ${capitalize(dataset.type)}`,
        '- Data object type: Image',
        `- No. of data objects: ${dataset.object_count}`,
        `- Metadata: ${metadata}`,
        '- Generated by: GenImage',
        '- Parameters: ',
        `  - Input datasets: ${input?.name ?? 'Unknown input dataset'}`,
        `  - Changed variables: ${record.gen_image.changed_variables.join(', ') || 'n.a.'}`,
        `  - Fixed variables: ${record.gen_image.fixed_variables.join(', ') || 'n.a.'}`,
        `  - Shape config: ${formatShapeConfig(record)}`,
        `  - Numeric variable config: ${formatVariableConfig(record)}`,
        `  - Number of images: ${record.gen_image.number_of_images}`,
        `  - Image size: ${record.gen_image.image_size[0]}x${record.gen_image.image_size[1]}`,
        `  - Output format: ${record.gen_image.output_format.toUpperCase()}`,
        `  - Sampling rule: ${record.gen_image.sampling_rule}`,
        `  - Random seed: ${record.gen_image.random_seed}`,
        `  - Labels recorded per image: ${formatRecordedLabels(record)}`,
        '',
        '## User comments:',
        record.comments.trim() || 'n.a.',
        '',
      ].join('\n'), buildGenImageSelectMetadata(formatRecordedLabels(record).split(', ').filter(Boolean).filter((item) => item !== 'n.a.'))),
    },
  ];
}

function formatMetadata(record: GenImageTransformationRecord) {
  return `Generated image dataset. ${record.gen_image.number_of_images} ${record.gen_image.image_size[0]}x${record.gen_image.image_size[1]} images. Changed variables: ${record.gen_image.changed_variables.join(', ') || 'n.a.'}. Fixed variables: ${record.gen_image.fixed_variables.join(', ') || 'n.a.'}. ${formatShapeSentence(record)} Labels recorded per image: ${formatRecordedLabels(record)}.`;
}

function formatShapeSentence(record: GenImageTransformationRecord) {
  if (record.gen_image.changed_variables.includes('shape')) {
    return `Shapes: ${record.gen_image.shape_values.join(', ')}.`;
  }

  return `Fixed shape: ${record.gen_image.fixed_shape_value}.`;
}

function formatShapeConfig(record: GenImageTransformationRecord) {
  if (record.gen_image.changed_variables.includes('shape')) {
    return `changed (${record.gen_image.shape_values.join(', ')})`;
  }

  return `fixed (${record.gen_image.fixed_shape_value})`;
}

function formatVariableConfig(record: GenImageTransformationRecord) {
  const items = RANGE_VARIABLE_CONFIG.map(({ key, label }) => {
    const changed = record.gen_image.changed_variables.includes(key);

    if (changed) {
      const range = getRange(record, key);
      return `${label}: changed range=(${range[0]}, ${range[1]}), levels=${getLevels(record, key)}`;
    }

    return `${label}: fixed value=${getFixedValue(record, key)}, levels=${getLevels(record, key)}`;
  });

  return items.join('; ');
}

function formatRecordedLabels(record: GenImageTransformationRecord) {
  const labels = new Set<string>();

  if (record.gen_image.changed_variables.includes('shape')) {
    labels.add('shape_label');
  }

  record.gen_image.changed_variables
    .filter((value) => value !== 'shape')
    .forEach((value) => labels.add(value));

  return Array.from(labels).join(', ') || 'n.a.';
}

function getRange(record: GenImageTransformationRecord, key: Exclude<(typeof VARIABLE_CONFIG)[number]['key'], 'shape'>) {
  switch (key) {
    case 'scale':
      return record.gen_image.scale_range;
    case 'size':
      return record.gen_image.size_range;
    case 'pos_x':
      return record.gen_image.pos_x_range;
    case 'pos_y':
      return record.gen_image.pos_y_range;
    case 'rotation':
      return record.gen_image.rotation_range;
    case 'grey':
      return record.gen_image.grey_range;
  }
}

function getLevels(record: GenImageTransformationRecord, key: Exclude<(typeof VARIABLE_CONFIG)[number]['key'], 'shape'>) {
  switch (key) {
    case 'scale':
      return record.gen_image.scale_levels;
    case 'size':
      return record.gen_image.size_levels;
    case 'pos_x':
      return record.gen_image.pos_x_levels;
    case 'pos_y':
      return record.gen_image.pos_y_levels;
    case 'rotation':
      return record.gen_image.rotation_levels;
    case 'grey':
      return record.gen_image.grey_levels;
  }
}

function getFixedValue(record: GenImageTransformationRecord, key: Exclude<(typeof VARIABLE_CONFIG)[number]['key'], 'shape'>) {
  switch (key) {
    case 'scale':
      return record.gen_image.scale_fixed_value;
    case 'size':
      return record.gen_image.size_fixed_value;
    case 'pos_x':
      return record.gen_image.pos_x_fixed_value;
    case 'pos_y':
      return record.gen_image.pos_y_fixed_value;
    case 'rotation':
      return record.gen_image.rotation_fixed_value;
    case 'grey':
      return record.gen_image.grey_fixed_value;
  }
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function sanitizeFilename(value: string) {
  return value.replace(/[^a-z0-9-_]+/gi, '_');
}
