import type { GenImageTransformationRecord } from '../transformations/transformation.types';

interface ReadmeFile {
  filename: string;
  content: string;
}

const VARIABLE_CONFIG = [
  { key: 'shape', label: 'shape' },
  { key: 'scale', label: 'scale' },
  { key: 'size', label: 'size' },
  { key: 'pos_x', label: 'pos_x' },
  { key: 'pos_y', label: 'pos_y' },
  { key: 'rotation', label: 'rotation' },
  { key: 'grey', label: 'grey' },
] as const;

const RANGE_VARIABLE_CONFIG = VARIABLE_CONFIG.filter((item) => item.key !== 'shape') as Array<{
  key: 'scale' | 'size' | 'pos_x' | 'pos_y' | 'rotation' | 'grey';
  label: string;
}>;

export function buildGenImageReadmes(record: GenImageTransformationRecord): ReadmeFile[] {
  const dataset = record.derived_datasets[0];
  const input = record.input_datasets[0];
  const metadata = formatMetadata(record);
  const selectedRangeSummary = formatSelectedRangeSummary(record);
  const selectedLevelSummary = formatSelectedLevelSummary(record);
  const selectedShapeValues = record.gen_image.changed_variables.includes('shape')
    ? record.gen_image.shape_values.join(', ') || 'n.a.'
    : 'n.a.';

  return [
    {
      filename: `${sanitizeFilename(dataset.name || dataset.draft_id)}-README.md`,
      content: [
        `# ${dataset.name} README`,
        '',
        '## Metadata',
        `- Dataset name: ${dataset.name}`,
        `- Type: ${capitalize(dataset.type)}`,
        '- Data object type: Image',
        `- No. of data objects: ${dataset.object_count}`,
        `- Metadata: ${metadata}`,
        '- Generated by: GenImage',
        '- Parameters: ',
        `  - Input datasets: ${input?.name ?? 'Unknown input dataset'}`,
        `  - Changed variables: ${record.gen_image.changed_variables.join(', ')}`,
        `  - Shape values: ${selectedShapeValues}`,
        `  - Number of images: ${record.gen_image.number_of_images}`,
        `  - Image size: ${record.gen_image.image_size[0]}x${record.gen_image.image_size[1]}`,
        `  - Output format: ${record.gen_image.output_format.toUpperCase()}`,
        `  - Sampling rule: ${record.gen_image.sampling_rule}`,
        `  - Random seed: ${record.gen_image.random_seed}`,
        `  - Variable ranges: ${selectedRangeSummary}`,
        `  - Discretization levels: ${selectedLevelSummary}`,
        `  - Labels recorded per image: ${formatRecordedLabels(record)}`,
        '',
        '## User comments:',
        record.comments.trim() || 'n.a.',
        '',
      ].join('\n'),
    },
  ];
}

function formatMetadata(record: GenImageTransformationRecord) {
  const shapeSentence = record.gen_image.changed_variables.includes('shape') && record.gen_image.shape_values.length
    ? ` Shapes: ${record.gen_image.shape_values.join(', ')}.`
    : '';

  return `Generated image dataset. ${record.gen_image.number_of_images} ${record.gen_image.image_size[0]}x${record.gen_image.image_size[1]} images. Changed variables: ${record.gen_image.changed_variables.join(', ')}.${shapeSentence} Labels recorded per image: ${formatRecordedLabels(record)}.`;
}

function formatRecordedLabels(record: GenImageTransformationRecord) {
  const labels = new Set<string>();

  if (record.gen_image.changed_variables.includes('shape')) {
    labels.add('shape_label');
  }

  record.gen_image.changed_variables
    .filter((value) => value !== 'shape')
    .forEach((value) => labels.add(value));

  return Array.from(labels).join(', ') || 'n.a.';
}

function formatSelectedRangeSummary(record: GenImageTransformationRecord) {
  const items = RANGE_VARIABLE_CONFIG
    .filter(({ key }) => record.gen_image.changed_variables.includes(key))
    .map(({ key, label }) => `${label} ${formatRange(record, key)}`);

  return items.join(', ') || 'n.a.';
}

function formatSelectedLevelSummary(record: GenImageTransformationRecord) {
  const items = RANGE_VARIABLE_CONFIG
    .filter(({ key }) => record.gen_image.changed_variables.includes(key))
    .map(({ key, label }) => `${label}=${formatLevel(record, key)}`);

  return items.join(', ') || 'n.a.';
}

function formatRange(record: GenImageTransformationRecord, key: Exclude<(typeof VARIABLE_CONFIG)[number]['key'], 'shape'>) {
  switch (key) {
    case 'scale':
      return `(${record.gen_image.scale_range[0]}, ${record.gen_image.scale_range[1]})`;
    case 'size':
      return `(${record.gen_image.size_range[0]}, ${record.gen_image.size_range[1]})`;
    case 'pos_x':
      return `(${record.gen_image.pos_x_range[0]}, ${record.gen_image.pos_x_range[1]})`;
    case 'pos_y':
      return `(${record.gen_image.pos_y_range[0]}, ${record.gen_image.pos_y_range[1]})`;
    case 'rotation':
      return `(${record.gen_image.rotation_range[0]}, ${record.gen_image.rotation_range[1]})`;
    case 'grey':
      return `(${record.gen_image.grey_range[0]}, ${record.gen_image.grey_range[1]})`;
  }
}

function formatLevel(record: GenImageTransformationRecord, key: Exclude<(typeof VARIABLE_CONFIG)[number]['key'], 'shape'>) {
  switch (key) {
    case 'scale':
      return String(record.gen_image.scale_levels);
    case 'size':
      return String(record.gen_image.size_levels);
    case 'pos_x':
      return String(record.gen_image.pos_x_levels);
    case 'pos_y':
      return String(record.gen_image.pos_y_levels);
    case 'rotation':
      return String(record.gen_image.rotation_levels);
    case 'grey':
      return String(record.gen_image.grey_levels);
  }
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function sanitizeFilename(value: string) {
  return value.replace(/[^a-z0-9-_]+/gi, '_');
}
