import type { DatasetRecord, DatasetType } from '../features/datasets/dataset.types';
import { appendSelectMetadataBlock, normalizeSelectMetadata, parseSelectMetadataBlock } from '../features/datasets/selectMetadata';
import { mockDatasets } from './datasets';

const readmeFiles = import.meta.glob('../../mock-datasets-local/*/README.md', {
  eager: true,
  import: 'default',
  query: '?raw',
}) as Record<string, string>;

const fallbackByName = new Map(mockDatasets.map((dataset) => [dataset.name, dataset]));

export const readmeBackedDatasets: DatasetRecord[] = mergeDatasets();

function mergeDatasets() {
  const parsed = Object.entries(readmeFiles)
    .map(([path, content]) => parseReadmeDataset(path, content))
    .filter((dataset): dataset is DatasetRecord => dataset !== null);

  return parsed.map((dataset) => ({
    ...(findFallbackDataset(dataset.name, dataset.readmeContent ?? '') ?? {}),
    ...dataset,
  }));
}

function parseReadmeDataset(path: string, content: string): DatasetRecord | null {
  const folderName = basename(path);
  const readmeName = getField(content, 'Dataset name') || folderName;
  const fallbackDataset = findFallbackDataset(folderName, content, readmeName);

  const typeValue = getField(content, 'Type') || fallbackDataset?.type || 'virtual';
  const dataObjectType = getField(content, 'Data object type') || fallbackDataset?.dataObjectType || fallbackDataset?.modality || 'Dataset object';
  const objectCountValue = getField(content, 'No. of data objects');
  const parsedObjectCount = parseInteger(objectCountValue);
  const metadata = getField(content, 'Metadata') || getField(content, 'Metadata summary') || fallbackDataset?.metadataSummary || 'README template not filled yet.';
  const parsedSelectMetadata = parseSelectMetadataBlock(content);
  const selectMetadata = normalizeSelectMetadata(parsedSelectMetadata ?? fallbackDataset?.selectMetadata);

  if (!folderName || !typeValue || !metadata) {
    return null;
  }

  const variableCount = parseInteger(getField(content, 'No. of variables / channels'));
  const labelCount = parseInteger(getField(content, 'No. of label headings'));
  const generatedBy = getField(content, 'Generated by');
  const inputDatasets = getNestedParameter(content, 'Input datasets');
  const source = generatedBy
    ? `${generatedBy}${inputDatasets ? ` from ${inputDatasets}` : ''}`
    : fallbackDataset?.source ?? 'Local README dataset';

  return {
    id: buildLocalId(folderName),
    name: folderName,
    type: normalizeType(String(typeValue)),
    source,
    modality: dataObjectType || 'Dataset object',
    dataObjectType: dataObjectType || undefined,
    keywordCount: fallbackDataset?.keywordCount ?? 0,
    objectCount: objectCountValue
      ? (parsedObjectCount ?? Number.NaN)
      : (fallbackDataset?.objectCount ?? Number.NaN),
    variableCount: variableCount ?? fallbackDataset?.variableCount ?? selectMetadata.columnNames?.length ?? 0,
    labelCount: labelCount ?? fallbackDataset?.labelCount ?? selectMetadata.labelHeadings.length,
    metadataSummary: metadata,
    readmeContent: appendSelectMetadataBlock(content.trim(), selectMetadata),
    selectMetadata,
  };
}

function findFallbackDataset(folderName: string, content: string, readmeName?: string) {
  return (
    fallbackByName.get(folderName)
    ?? (readmeName ? fallbackByName.get(readmeName) : undefined)
    ?? findDatasetByHeuristic(folderName, content)
  );
}

function findDatasetByHeuristic(folderName: string, content: string) {
  if (folderName === 'LibriSpeechClean360') {
    return fallbackByName.get('Speech-Clean');
  }

  if (folderName === 'WHAMNoise') {
    return fallbackByName.get('Speech-Noise Clips');
  }

  if (folderName === 'Libri2Mix') {
    return fallbackByName.get('Speech-Mixed');
  }

  if (folderName === 'WindFarmABC') {
    return fallbackByName.get('WindFarmsABC');
  }

  if (folderName === 'WindFarmABC_sel') {
    return fallbackByName.get('WindFarmA-Filtered');
  }

  if (folderName === 'WindFarmABC_sel_sel') {
    return fallbackByName.get('WindFarmB-Labeled');
  }

  if (folderName === 'WindFarmABC_sel_sel_1_trn') {
    return fallbackByName.get('WindFarmB-Labeled-Train');
  }

  if (folderName === 'WindFarmABC_sel_sel_1_tst') {
    return fallbackByName.get('WindFarmB-Labeled-Test');
  }

  if (folderName === 'WindFarmABC_sel_sel_1_val') {
    return fallbackByName.get('WindFarmB-Labeled-Validate');
  }

  if (content.includes('speech') || content.includes('WHAM') || content.includes('Libri')) {
    return fallbackByName.get('Speech-Mixed') ?? fallbackByName.get('Speech-Clean') ?? fallbackByName.get('Speech-Noise Clips');
  }

  return undefined;
}

function getField(content: string, label: string) {
  const escaped = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = content.match(new RegExp(`^- ${escaped}:[\t ]*([^\r\n]*)$`, 'm'));
  return cleanFieldValue(match?.[1] ?? '');
}

function getNestedParameter(content: string, label: string) {
  const escaped = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = content.match(new RegExp(`^\s+- ${escaped}:[\t ]*([^\r\n]*)$`, 'm'));
  return cleanFieldValue(match?.[1] ?? '');
}

function cleanFieldValue(value: string) {
  const trimmed = value.trim();

  if (!trimmed) {
    return '';
  }

  if (/^-[\t ]+[A-Za-z].*:[\t ]*$/.test(trimmed)) {
    return '';
  }

  return trimmed;
}

function normalizeType(value: string): DatasetType {
  return value.trim().toLowerCase() === 'physical' ? 'physical' : 'virtual';
}

function parseInteger(value: string) {
  const match = value.match(/-?\d+/);
  return match ? Number(match[0]) : null;
}

function basename(path: string) {
  return path.split('/').slice(-2, -1)[0] ?? 'Dataset';
}

function buildLocalId(name: string) {
  return `LOCAL-${name.replace(/[^a-z0-9]+/gi, '-').replace(/(^-|-$)/g, '').toUpperCase()}`;
}
