import type { DatasetRecord, DatasetType } from '../features/datasets/dataset.types';
import { mockDatasets } from './datasets';

const readmeFiles = import.meta.glob('../../mock-datasets-local/*/README.md', {
  eager: true,
  import: 'default',
  query: '?raw',
}) as Record<string, string>;

const fallbackByName = new Map(mockDatasets.map((dataset) => [dataset.name, dataset]));

export const readmeBackedDatasets: DatasetRecord[] = mergeDatasets();

function mergeDatasets() {
  const parsed = Object.entries(readmeFiles)
    .map(([path, content]) => parseReadmeDataset(path, content))
    .filter((dataset): dataset is DatasetRecord => dataset !== null);

  const parsedNames = new Set(parsed.map((dataset) => dataset.name));

  return [
    ...parsed.map((dataset) => ({
      ...(fallbackByName.get(dataset.name) ?? {}),
      ...dataset,
      selectMetadata: dataset.selectMetadata ?? fallbackByName.get(dataset.name)?.selectMetadata,
    })),
    ...mockDatasets.filter((dataset) => !parsedNames.has(dataset.name)),
  ];
}

function parseReadmeDataset(path: string, content: string): DatasetRecord | null {
  if (content.includes('## Core Fields')) {
    return null;
  }

  const name = getField(content, 'Dataset name') || basename(path);
  const typeValue = getField(content, 'Type');
  const dataObjectType = getField(content, 'Data object type');
  const objectCountValue = getField(content, 'No. of data objects');
  const metadata = getField(content, 'Metadata') || getField(content, 'Metadata summary');

  if (!name || !typeValue || !metadata || !objectCountValue) {
    return null;
  }

  const variableCount = parseInteger(getField(content, 'No. of variables / channels'));
  const labelCount = parseInteger(getField(content, 'No. of label headings'));
  const generatedBy = getField(content, 'Generated by');
  const inputDatasets = getNestedParameter(content, 'Input datasets');
  const source = generatedBy
    ? `${generatedBy}${inputDatasets ? ` from ${inputDatasets}` : ''}`
    : 'Local README dataset';

  return {
    id: fallbackByName.get(name)?.id ?? buildLocalId(name),
    name,
    type: normalizeType(typeValue),
    source,
    modality: dataObjectType || 'Dataset object',
    dataObjectType: dataObjectType || undefined,
    keywordCount: fallbackByName.get(name)?.keywordCount ?? 0,
    objectCount: parseInteger(objectCountValue) ?? 0,
    variableCount: variableCount ?? fallbackByName.get(name)?.variableCount ?? 0,
    labelCount: labelCount ?? fallbackByName.get(name)?.labelCount ?? 0,
    metadataSummary: metadata,
    readmeContent: content.trim(),
  };
}

function getField(content: string, label: string) {
  const escaped = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = content.match(new RegExp(`^- ${escaped}:\\s*(.*)$`, 'm'));
  return match?.[1]?.trim() ?? '';
}

function getNestedParameter(content: string, label: string) {
  const escaped = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = content.match(new RegExp(`^\\s+- ${escaped}:\\s*(.*)$`, 'm'));
  return match?.[1]?.trim() ?? '';
}

function normalizeType(value: string): DatasetType {
  return value.trim().toLowerCase() === 'physical' ? 'physical' : 'virtual';
}

function parseInteger(value: string) {
  const match = value.match(/-?\d+/);
  return match ? Number(match[0]) : null;
}

function basename(path: string) {
  return path.split('/').slice(-2, -1)[0] ?? 'Dataset';
}

function buildLocalId(name: string) {
  return `LOCAL-${name.replace(/[^a-z0-9]+/gi, '-').replace(/(^-|-$)/g, '').toUpperCase()}`;
}
