import type { BlendTransformationRecord } from '../transformations/transformation.types';
import { buildBlendMetadataSummary } from './blendMetadata';
import { formatReadmeTimestamp } from '../../lib/readmeTimestamp';
import { appendSelectMetadataBlock } from '../datasets/selectMetadata';

interface ReadmeFile {
  filename: string;
  content: string;
}

export function buildBlendReadmes(record: BlendTransformationRecord): ReadmeFile[] {
  const primaryDataset = record.input_datasets.find((dataset) => dataset.id === record.blend.primary_dataset_id) ?? null;
  const auxiliaryDatasets = record.input_datasets.filter((dataset) => record.blend.auxiliary_dataset_ids.includes(dataset.id));

  return record.derived_datasets.map((dataset) => {
    const content = appendSelectMetadataBlock([
      `# ${dataset.name} README`,
      '',
      '## Metadata',
      `- Dataset name: ${dataset.name}`,
      `- Timestamp: ${formatReadmeTimestamp(record.created_at)}`,
      `- Type: ${capitalize(dataset.type)}`,
      `- Data object type: ${primaryDataset?.dataObjectType ?? primaryDataset?.modality ?? 'Data object'}`,
      `- No. of data objects: ${dataset.object_count}`,
      `- Metadata: ${buildBlendMetadataSummary(primaryDataset, auxiliaryDatasets, record.blend.auxiliary_fraction)}`,
      '- Generated by: Blend',
      '- Parameters:',
      `  - Input datasets: ${record.input_datasets.map((item) => item.name).join(', ')}`,
      `  - Primary dataset: ${primaryDataset?.name ?? 'n.a.'}`,
      `  - Auxiliary datasets: ${auxiliaryDatasets.map((item) => item.name).join(', ') || 'n.a.'}`,
      `  - Noise pool fraction: ${formatPercentage(record.blend.auxiliary_fraction)}`,
      `  - Selection rule: ${formatSelectionRule(record.blend.selection_rule)}`,
      `  - Assignment rule: ${formatAssignmentRule(record.blend.assignment_rule)}`,
      `  - Signal scaling rule: ${formatSignalScalingRule(record.blend.signal_scaling_rule)}`,
      `  - Merge rule: ${formatMergeRule(record.blend.merge_rule)}`,
      '',
      '## User comments:',
      record.comments.trim() || 'n.a.',
      '',
    ].join('\n'), primaryDataset?.selectMetadata);

    return {
      filename: `${dataset.name}_README.md`,
      content,
    };
  });
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function formatPercentage(value: number) {
  const percentage = value * 100;
  const formatted = Number.isInteger(percentage) ? String(percentage) : percentage.toFixed(2).replace(/0+$/, '').replace(/\.$/, '');
  return `${formatted}%`;
}

function formatSelectionRule(value: BlendTransformationRecord['blend']['selection_rule']) {
  switch (value) {
    case 'all_objects':
      return 'All objects';
    case 'random_without_replacement':
    default:
      return 'Random without replacement';
  }
}

function formatAssignmentRule(value: BlendTransformationRecord['blend']['assignment_rule']) {
  switch (value) {
    case 'cyclic_reuse':
      return 'Cyclic reuse';
    case 'random_with_reuse':
    default:
      return 'Random with reuse';
  }
}

function formatSignalScalingRule(value: BlendTransformationRecord['blend']['signal_scaling_rule']) {
  switch (value) {
    case 'target_snr':
    default:
      return 'Target SNR';
  }
}

function formatMergeRule(value: BlendTransformationRecord['blend']['merge_rule']) {
  switch (value) {
    case 'add_signals':
    default:
      return 'Add signals';
  }
}
